In [16]:
# HW Exercise 1: Write a Python function which will sum all the following listed items (5,8,2,4,7,9)

n_list=[5,8,2,4,7,9]

def function_sum(x):
    sum = x[0]
    for i in range (1, len(x)):
        sum = sum + x[i]
    return sum

function_sum(n_list)

35

In [17]:
# HW Exercise 2: Write a Python function which will find the product/multiply the items in the following list: (4,3,5,6,2)

n_list2=[4,3,5,6,2]

def function_product(x):
    product = x[0]
    for i in range (1, len(x)):
        product = product*x[i]
    return product

function_product(n_list2)

720

In [19]:
# HW Exercise: Given the following array:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [24]:
# a) Sort the flattened array
flat_array=array_hw.flatten()
print('Flattened array')
print(flat_array)
print('')
print('Sort the flattened array')
np.sort(flat_array, axis=None)

Flattened array
[5 5 8 8 9 8 7 7 5 3 5 7 8 7 8 4 2 6 9 9 7 3 1 4]

Sort the flattened array


array([1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9,
       9, 9])

In [31]:
# b) Sort the second column
print('Array_hw:')
print(array_hw)
print('')
print('Slice the second column:')
array_2nd_column=array_hw[...,1]
print(array_2nd_column)
print('')
print('Sort the second column:')
np.sort(array_2nd_column)

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Slice the second column:
[5 7 7 9]

Sort the second column:


array([5, 7, 7, 9])

In [32]:
# c) Sort the third row
print('Array_hw:')
print(array_hw)
print('')
print('Slice the third row:')
array_3rd_row=array_hw[2,...]
print(array_3rd_row)
print('')
print('Sort the third row:')
np.sort(array_3rd_row)

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Slice the third row:
[8 7 8 4 2 6]

Sort the third row:


array([2, 4, 6, 7, 8, 8])

In [41]:
# d) Extract the second row onwards
print ('Array_hw:')
print (array_hw)
print('')
print('Extract the second row onwards:')
array_2nd_row_on=array_hw[1:,...]
print(array_2nd_row_on)

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Extract the second row onwards:
[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [36]:
# e) Extract the third column onwards
print('Array_hw:')
print(array_hw)
print('')
print('Extract the third column onwards:')
array_3rd_column_on=array_hw[...,2:]
print(array_3rd_column_on)

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Extract the third column onwards:
[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]


In [40]:
# f) obtain the square of array_hw
print('Array_hw:')
print(array_hw)
print('')
print('Obtain the square of array_hw:')
np.sqrt(array_hw)

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Obtain the square of array_hw:


array([[2.23606798, 2.23606798, 2.82842712, 2.82842712, 3.        ,
        2.82842712],
       [2.64575131, 2.64575131, 2.23606798, 1.73205081, 2.23606798,
        2.64575131],
       [2.82842712, 2.64575131, 2.82842712, 2.        , 1.41421356,
        2.44948974],
       [3.        , 3.        , 2.64575131, 1.73205081, 1.        ,
        2.        ]])

In [43]:
# g)Slice the element from the third row and fourth column position 3X4
print('Array_hw:')
print(array_hw)
print('')
print('Slice the element from the third row and fourth column position 3X4:')
print(array_hw[2,3])

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Slice the element from the third row and fourth column position 3X4:
4


In [44]:
# f) obtain the total sum of array_hw
print('Array_hw:')
print(array_hw)
print('')
print('Obtain the total sum of array_hw:')
print(array_hw.sum())

Array_hw:
[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Obtain the total sum of array_hw:
145


In [50]:
# h) How many dimentions does array_hw have?
print('How many dimentions does array_hw have?')
array_hw.ndim

How many dimentions does array_hw have?


2

In [48]:
# i) What is the data type listed in array_hw?
print('What is the data type listed in array_hw?')
type(array_hw)

What is the data type listed in array_hw?


numpy.ndarray

In [51]:
# j) What is the size of the memory in bytes consumed by all the elements in array_hw?
array_hw.nbytes

96